---

roles:
  - name: galaxyproject.slurm
    version: 1.0.5
  - name: galaxyproject.cvmfs
    version: 0.4.0

collections:
  - name: galaxyproject.general
    version: 1.4.2
  - name: artis3n.tailscale
    version: 1.2.0
