---

roles:
  - name: galaxyproject.slurm
    version: 1.0.5
  - name: galaxyproject.cvmfs
    version: 0.4.0
  - name: artis3n.tailscale
    version: v5.0.1

collections:
  - name: galaxyproject.general
    version: 1.4.1
