---

slurmscale_users:
  - name: g2main
    uid: 819800
    group: G-803372
  - name: g2test
    uid: 819456
    group: G-803372
  - name: idc
    uid: 808
    group: idc

slurmscale_groups:
  - name: G-803372
    gid: 803372
  - name: idc
    gid: 808

slurmscale_packages:
  #- autofs
  - lzo
  - git
  - apptainer
  - python39

slurmscale_stop_services:
  - tuned
  - rsyslog
  #- auditd

slurmscale_resume_files:
  - path: /etc/slurm/slurm.conf
  - path: /etc/slurm/prolog.bash
    mode: "0755"
  - path: /etc/slurm/prolog.sh
    mode: "0755"
  - path: /etc/slurm/epilog.sh
    mode: "0755"

cvmfs_role: client
# this is overridden on instance spawn anyway
cvmfs_quota_limit: 8192

slurm_roles:
  - exec

slurm_munge_key: files/slurm/munge.key

slurm_cgroup_config:
  CgroupAutomount: yes
  ConstrainCores: yes
  ConstrainRAMSpace: yes
  ConstrainSwapSpace: yes

galaxy_cvmfs_repos_enabled: true

slurm_user:
  uid: 40302
  gid: 40302
  comment: 'Slurm Workload Manager'
  home: /var/lib/slurm
  shell: /bin/bash
