---

# use the key written out by the openstack role
#os_secrets:
#  - dest: "{{ os_key_name }}.pem"
#    content: "{{ openstack_privatekeys.admin }}"
#ansible_ssh_private_key_file: "{{ inventory_dir }}/{{ os_key_name }}.pem"

os_image: Featured-RockyLinux9
os_flavor: m3.medium
os_auto_ip: false

ceph_mount_state: present

slurm_start_services: false

tailscale_up_skip: true

# Used by the image generation playbook, instances names match the image name
usegalaxy_node_image_name: "{{ inventory_hostname }}"

# https://github.com/galaxyproject/galaxy/pull/18863
galaxy_job_execution_pip_name: git+https://github.com/natefoo/galaxy.git@container-monitor-retry-post#egg=galaxy-job-execution&subdirectory=packages/job_execution
